
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/wheelersadvice:$COMMIT_SHA', '.']
    timeout: 300s

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wheelersadvice:$COMMIT_SHA']
    timeout: 300s

  - name: 'gcr.io/cloud-builders/git'
    args:
      - '-c'
      - |
        git clone https://github.com/wheelers-websites/CloudGuruChallenge_21.08-env.git
        git checkout test
        echo "gcr.io/$PROJECT_ID/wheelersadvice:$COMMIT_SHA" > deployment/app/image.txt
        cat deployment/app/image.txt
        git add deployment/app/image.txt
        git commit -m "app deployment for $COMMIT_SHA"
        git push --set-upstream origin test
    entrypoint: /bin/sh
    timeout: 300s

#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    args: ['run', 'deploy', 'wheelersadvice', '--image', 'gcr.io/$PROJECT_ID/wheelersadvice:$COMMIT_SHA', '--region', 'us-central1']
#    entrypoint: gcloud
#    timeout: 300s
