
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/wheelersadvice:$COMMIT_SHA', '.']
    timeout: 300s

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wheelersadvice:$COMMIT_SHA']
    timeout: 300s

  - name: 'gcr.io/cloud-builders/git'
    args:
      - '-c'
      - |
        git config --global user.email "98767786228@cloudbuild.gserviceaccount.com"
        git config --global user.name "Cloud Build Service Account"
        gcloud source repos clone wheelersadvice/cicd/app --project=cloudguruchallenge-2108
        cd wheelersadvice/cicd/app
        git checkout candidate
        echo "gcr.io/$PROJECT_ID/wheelersadvice:$COMMIT_SHA" > image.txt
        cat image.txt
        git add image.txt
        git commit -m "app deployment for $COMMIT_SHA"
        git push -u origin candidate
    entrypoint: /bin/sh
    timeout: 300s

#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    args: ['run', 'deploy', 'wheelersadvice', '--image', 'gcr.io/$PROJECT_ID/wheelersadvice:$COMMIT_SHA', '--region', 'us-central1']
#    entrypoint: gcloud
#    timeout: 300s
