
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: node
    args: ['install']
    dir: web
    entrypoint: npm
    timeout: 300s

  - name: node
    args: ['run', 'build']
    dir: web
    entrypoint: npm
    timeout: 300s

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['rsync', '-c', '-d', '-r', 'dist/', 'gs://wheelersadvice']
    dir: web
    entrypoint: gsutil
    timeout: 300s

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['compute', 'url-maps', 'invalidate-cdn-cache', 'wheelersadvice', '--path', '/*']
    entrypoint: gcloud
    timeout: 300s
