
options:
  logging: CLOUD_LOGGING_ONLY

steps:
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/$PROJECT_ID/wheelersadvice:$COMMIT_SHA', '.']
#    dir: app
#    timeout: 300s
#
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'gcr.io/$PROJECT_ID/wheelersadvice:$COMMIT_SHA']
#    dir: app
#    timeout: 300s
#
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    args: ['run', 'deploy', 'wheelersadvice', '--image', 'gcr.io/$PROJECT_ID/wheelersadvice:$COMMIT_SHA', '--region', 'us-central1']
#    dir: app
#    entrypoint: gcloud
#    timeout: 300s
